### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by alphapapa** [nickmccurdy/add-hooks#2]
Hi,

I'm interested in this package, but since there are no examples in the readme, I'd have to dig into the code to find out how to use it.  Please provide some examples.  :)

**Comment by nickserv** [comment]
Sorry about that, I used to have examples in the readme but I moved them to the package source as comments and docstrings because that's what Emacs and MELPA see.

Please review the docstrings in [add-hooks.el](https://github.com/nickmccurdy/add-hooks/blob/master/add-hooks.el) (starting at lines 45 and 69). Do you think it would be enough for me to format these for the readme and paste them at the bottom, or do you want more examples than I currently have?

**Comment by alphapapa** [comment]
Those seem fine to me. Thanks.
